---
title: "Dynamic Report"
author: "Ngun Tial, Ella Shen, Yiwei Shi, Xinyue Hou, Pengfei Lou"
date: "`r Sys.Date()`"
output: html_document
params:
  project: "subproject2" # you can also change 'subproject1' into 'subproject2'.
---
```{r, set-chunk-opts, include = FALSE}
library(knitr)

pacman::p_load(
  htmltools
)
opts_chunk$set(
  echo = FALSE, warning = FALSE, message = FALSE
)
```

```{r}
path<-here::i_am(
  "dynamic_report.Rmd"
)
```

```{r}

if(params$project == "subproject1") {
  data <- readRDS(file = here::here("data/data_clean.rds"))
} else if(params$project == "subproject2") {
  data <- readRDS(file = here::here("data/data_clean.rds"))
}

```


```{r echo=FALSE, results='asis'}

if(params$project == "subproject1") {
  cat('<iframe src="subproject1/report.html" style="width:100%; height:600px;"></iframe>')
} else if(params$project == "subproject2") {
  cat('<iframe src="subproject2/report.html" style="width:100%; height:600px;"></iframe>')
}

```



